# Site settings
title: "bizarrechaos"
bye_message: ""
baseurl: "/"
url: "https://bizarrechaos.github.io"
#disqus: bizarrechaos

# Header settings
nick: "bizarrechaos"
mail:
    domain: "bizarrechaos"
    ext: "com"
source_code:
    server: "github.com"
    nick: "bizarrechaos"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
