# Site settings
title: "bizarrechaos"
bye_message: ""
baseurl: "https://bizarrechaos.com/"
url: "https://bizarrechaos.com"
#disqus: bizarrechaos

# Header settings
nick: "bizarrechaos"
mail:
    domain: "bizarrechaos"
    ext: "com"
source_code:
    server: "github.com"
    nick: "bizarrechaos"
fingerprint_key: "894F E13F C25A 47FF 1AE4  F643 452A D28A A3D2 C6B6"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
